#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Docopt\Handler;
use Hexlet\Code\Differ;

$doc = <<<'DOCOPT'
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]
DOCOPT;

$handler = new Handler();
$args = $handler->handle($doc);

if (isset($args['--help']) && $args['--help'] || isset($args['-h']) && $args['-h']) {
    echo $doc;
    exit(0);
}

if (isset($args['--version']) && $args['--version'] || isset($args['-v']) && $args['-v']) {
    echo "gendiff version 1.0.0\n";
    exit(0);
}

// Обработка основных аргументов
if (isset($args['<firstFile>']) && isset($args['<secondFile>'])) {
    $firstFile = $args['<firstFile>'];
    $secondFile = $args['<secondFile>'];
    $format = isset($args['--format']) ? $args['--format'] : 'stylish';
    
    try {
        $diff = Differ::genDiff($firstFile, $secondFile, $format);
        echo $diff . "\n";
        
    } catch (\Exception $e) {
        echo "Error: " . $e->getMessage() . "\n";
        exit(1);
    }
    
    exit(0);
} 